require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
-- require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.indentline"
require "user.alpha"
require "user.lsp"
require "user.leap"
require "user.whichkey"
require "user.cheatsheet"
require "user.mind"
require "user.neorg"
require "user.copilot"
-- require "user.dap"
-- require "user.rosnvim"
-- require "user.neogit"
