require('settings')
require('packer-config')
require('colorschemes-config.gruvbox')
require('nvim-tree-config')
require('mappings')
require('lsp-config.nvim-lspconfig')
require('lsp-config.nvim-cmp')
-- require('lsp-config.lsp-one')
require('lsp-config.null-ls')
require('lualine-config')
require('treesitter-config')
require('shade-config')
require('whichkey-config')
