require("settings")
require("autocmds")
require("packer-config.plugins")
require("colorschemes-config.gruvbox")
require("nvim-tree-config")
require("mappings")

--require('lsp.lsp-one')
require("barbar")

require("lsp.null-ls")
require("lsp.lsp")
require("lsp.cmp")
require("lualine-config")
require("treesitter-config")
require("whichkey-config")
require("git_diffview")
require("neogit.ngit")
